### PR TITLE
Don't override manager if it's in the arguments.

### PR DESCRIPTION
**Pull request by philb61**
Fixes: https://bitbucket.org/neithere/django-autoslug/issues/34/django-migrations-fail-i

### CODE REVIEW

**Comment by neithere** [comment]
Thank you! Looks good. Do you think you could also add a test to maintain the level of coverage?

**Comment by philb61** [comment]
Done, see https://github.com/philb61/django-autoslug/commit/f6d1a12a830e009554681223b45c799afff4e67f

**Comment by neithere** [comment]
Great, thanks a lot!

**Comment by vstoykov** [comment]
@neithere I see that there is no new version for a long time. This patch is needed for working with Django1.8+

P.S. I know that the issue tracker is in Bibucket, but I have some trouble with logging in because of their account migration process.

**Comment by philb61** [comment]
I agree.  Right now, we use a specific commit in the file we use to tell pip what to install.  It would be much nicer to be able to tell it to use a correct version.

**Pull request merged**
